In [2]:
import requests
import json
import zipfile, io
import pandas as pd
import folium
import os

DATA_PATH = '../data'
RAW_DATA_PATH = os.path.join(DATA_PATH, 'raw')
INT_DATA_PATH = os.path.join(RAW_DATA_PATH,'intermediate')

TFL_API = 'https://api.tfl.gov.uk'
STATION_DATA_API = TFL_API + '/stationdata/tfl-stationdata-detailed.zip'
SHPBUM_STATION_QUERY =  TFL_API +'/Stoppoint/Search/Shepherd?modes=tube'
STOPPOINT_TYPES =  TFL_API +'/StopPoint/Meta/StopTypes'
SHPBUM_ARRIVALS =  TFL_API +'/StopPoint/940GZZLUSBM/Arrivals'
STATION_DISTANCES_PATH = os.path.join(RAW_DATA_PATH, 'InterStationDistanceAndTimeDump/InterStationTimesAndDistancesDump.csv')

def jprint(obj):
    # create a formatted string of the Python JSON object
    text = json.dumps(obj, sort_keys=True, indent=2)
    print(text)

In [3]:
st_cols = ['Line', 'Direction', 'Station from (A)', 'Station to (B)',
       'Distance (Kms)', 'Un-impeded Running Time (Mins)',
       'AM peak (0700-1000) Running Time (Mins)',
       'Inter peak (1000 - 1600) Running time (mins)']
st_df = pd.read_csv(STATION_DISTANCES_PATH, header=1, usecols= st_cols)
st_df = st_df.loc[st_df['Line'].notnull()]
st_df

,Line,Direction,Station from (A),Station to (B),Distance (Kms),Un-impeded Running Time (Mins),AM peak (0700-1000) Running Time (Mins),Inter peak (1000 - 1600) Running time (mins)
0,Bakerloo,Southbound,HARROW & WEALDSTONE,KENTON,1.74,2.23,2.50,2.50
1,Bakerloo,Southbound,KENTON,SOUTH KENTON,1.40,1.88,2.00,2.00
2,Bakerloo,Southbound,SOUTH KENTON,NORTH WEMBLEY,0.90,1.50,1.50,1.50
3,Bakerloo,Southbound,NORTH WEMBLEY,WEMBLEY CENTRAL,1.27,1.92,2.06,2.06
4,Bakerloo,Southbound,WEMBLEY CENTRAL,STONEBRIDGE PARK,1.71,2.23,3.13,3.13
...,...,...,...,...,...,...,...,...
738,East London,Southbound,WAPPING,ROTHERHITHE,0.51,1.17,1.50,1.50
739,East London,Southbound,ROTHERHITHE,CANADA WATER,0.32,0.93,1.00,1.00
740,East London,Southbound,CANADA WATER,SURREY QUAYS,0.55,1.70,2.00,2.09
741,East London,Southbound,SURREY QUAYS,NEW CROSS,2.27,4.27,4.50,4.50
742,East London,Southbound,SURREY QUAYS,NEW CROSS GATE,2.04,3.88,3.50,3.50

In [23]:
st_df.sort_values(by='Distance (Kms)',ascending=False).loc[st_df['Station from (A)']=="SHEPHERDS BUSH"]

,Line,Direction,Station from (A),Station to (B),Distance (Kms),Un-impeded Running Time (Mins),AM peak (0700-1000) Running Time (Mins),Inter peak (1000 - 1600) Running time (mins)
134,Central,Westbound,SHEPHERDS BUSH,WHITE CITY,1.16,2.77,3.74,3.97
503,H & C,Eastbound,SHEPHERDS BUSH,LATIMER ROAD,1.01,1.63,2.00,2.00
60,Central,Eastbound,SHEPHERDS BUSH,HOLLAND PARK,0.87,1.37,1.75,1.75
553,H & C,Westbound,SHEPHERDS BUSH,GOLDHAWK ROAD,0.51,1.15,1.00,1.00